Catkin-ProjectName: object_recognition_capture
Version: 0.2.4
Description: Capture is a set of tools to capture objects in 3D and perform odometry
Author: Ethan Rublee <erublee@willowgarage.com>, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com/recognition

Depends: catkin, boost, ecto, ecto_opencv, object_recognition_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
